version: 2
updates:
  # Maven dependencies - HIGH PRIORITY for security
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 15
    labels:
      - "dependencies"
      - "maven"
      - "security"
    commit-message:
      prefix: "security(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    # Assignees for security-critical updates
    assignees:
      - "IronKnight66"  # Replace with actual security team members
    # Reviewers for dependency updates
    reviewers:
      - "IronKnight66"  # Replace with actual reviewers
    # Group related updates for easier review
    groups:
      # Security-focused libraries
      security-libraries:
        patterns:
          - "*security*"
          - "*crypto*"
          - "*auth*"
          - "org.springframework.security*"
          - "org.apache.shiro*"
          - "com.auth0*"
          - "io.jsonwebtoken*"
        update-types:
          - "minor"
          - "patch"
          - "security"
      # Spring Framework ecosystem
      spring-framework:
        patterns:
          - "org.springframework*"
          - "org.springframework.boot*"
        update-types:
          - "minor"
          - "patch"
      # Testing dependencies (lower priority)
      test-dependencies:
        patterns:
          - "*junit*"
          - "*mockito*"
          - "*testcontainers*"
          - "*hamcrest*"
        update-types:
          - "minor"
          - "patch"
    # Allow specific dependency updates (removed OWASP ignore for security scanning)
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Only ignore non-security updates for specific packages
    ignore:
      # Only ignore major version updates for these (allow security patches)
      - dependency-name: "org.springframework*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.boot*"
        update-types: ["version-update:semver-major"]

  # Maven dependencies - SECURITY-ONLY updates (high frequency)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security-patch"
      - "critical"
      - "auto-merge-candidate"
    commit-message:
      prefix: "security(critical)"
      include: "scope"
    assignees:
      - "IronKnight66"
    # Only security updates
    allow:
      - dependency-type: "direct"
        update-types: ["security"]
      - dependency-type: "indirect"
        update-types: ["security"]
    groups:
      critical-security:
        patterns:
          - "*"
        update-types:
          - "security"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "automation"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    assignees:
      - "IronKnight66"  # Replace with DevOps team members

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
    commit-message:
      prefix: "docker(deps)"
      include: "scope"
    assignees:
      - "IronKnight66"  # Replace with infrastructure team members

  # NPM/Node.js dependencies (if any exist)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    commit-message:
      prefix: "deps(npm)"
      include: "scope"
    # Group JavaScript updates
    groups:
      javascript-security:
        patterns:
          - "*security*"
          - "*crypto*"
          - "@types/*"
        update-types:
          - "security"
          - "patch"
      javascript-dev:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*jest*"
          - "*babel*"
          - "*webpack*"
        update-types:
          - "minor"
          - "patch"
